name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend_compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Grant execute permission for Maven Wrapper
        run: chmod a+x backend/mvnw
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Compile backend
        run: cd backend && ./mvnw clean compile

  backend_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Grant execute permission for Maven Wrapper
        run: chmod a+x backend/mvnw
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Run tests
        run: cd backend && ./mvnw test
      - name: Archive test reports
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-reports
          path: backend/target/surefire-reports/

  backend_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Grant execute permission for Maven Wrapper
        run: chmod a+x backend/mvnw
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Package backend
        run: cd backend && ./mvnw package -DskipTests
      - name: Upload Maven artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifacts
          path: backend/target/*.jar

  backend_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run:
          cd backend &&
          docker build . --file Dockerfile --tag ghcr.io/lanuris/bik-tjv/backend:latest &&
          docker push ghcr.io/lanuris/bik-tjv/backend:latest

  backend_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Grant execute permission for Maven Wrapper
        run: chmod a+x backend/mvnw
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Generate Javadoc
        run: cd backend && ./mvnw javadoc:javadoc -DskipTests
      - name: Upload Javadoc
        uses: actions/upload-artifact@v4
        with:
          name: backend-javadoc
          path: backend/target/site/apidocs/*

  frontend_compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Grant execute permission for Maven Wrapper
        run: chmod a+x frontend/mvnw
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/frontend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Compile frontend
        run: cd frontend && ./mvnw clean compile

  frontend_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Grant execute permission for Maven Wrapper
        run: chmod a+x frontend/mvnw
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/frontend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Run tests
        run: cd frontend && ./mvnw test
      - name: Archive test reports
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-reports
          path: frontend/target/surefire-reports/

  frontend_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Grant execute permission for Maven Wrapper
        run: chmod a+x frontend/mvnw
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/frontend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Package frontend
        run: cd frontend && ./mvnw package -DskipTests
      - name: Upload Maven artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifacts
          path: frontend/target/*.jar

  frontend_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: |
          cd frontend 
          docker build . --file Dockerfile --tag ghcr.io/lanuris/bik-tjv/frontend:latest 
          docker push ghcr.io/lanuris/bik-tjv/frontend:latest
